config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :homes

  resources :roofs

  resources :lands

  resources :heating_systems

  resources :windows

  resources :floors

  resources :doors

  resources :insulations

  resources :appliances

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appliance.rb
class Appliance < ActiveRecord::Base
end

app/models/door.rb
class Door < ActiveRecord::Base
end

app/models/floor.rb
class Floor < ActiveRecord::Base
end

app/models/heating_system.rb
class HeatingSystem < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
  has_one :user
end

app/models/insulation.rb
class Insulation < ActiveRecord::Base
end

app/models/land.rb
class Land < ActiveRecord::Base
end

app/models/roof.rb
class Roof < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  belongs_to :home
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first

    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/window.rb
class Window < ActiveRecord::Base
end

app/controllers/heating_systems_controller.rb
class HeatingSystemsController < ApplicationController
  before_action :set_heating_system, only: [:show, :edit, :update, :destroy]

  # GET /heating_systems
  # GET /heating_systems.json
  def index
    @heating_systems = HeatingSystem.all
  end

  # GET /heating_systems/1
  # GET /heating_systems/1.json
  def show
  end

  # GET /heating_systems/new
  def new
    @heating_system = HeatingSystem.new
  end

  # GET /heating_systems/1/edit
  def edit
  end

  # POST /heating_systems
  # POST /heating_systems.json
  def create
    @heating_system = HeatingSystem.new(heating_system_params)

    respond_to do |format|
      if @heating_system.save
        format.html { redirect_to @heating_system, notice: 'Heating system was successfully created.' }
        format.json { render :show, status: :created, location: @heating_system }
      else
        format.html { render :new }
        format.json { render json: @heating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heating_systems/1
  # PATCH/PUT /heating_systems/1.json
  def update
    respond_to do |format|
      if @heating_system.update(heating_system_params)
        format.html { redirect_to @heating_system, notice: 'Heating system was successfully updated.' }
        format.json { render :show, status: :ok, location: @heating_system }
      else
        format.html { render :edit }
        format.json { render json: @heating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heating_systems/1
  # DELETE /heating_systems/1.json
  def destroy
    @heating_system.destroy
    respond_to do |format|
      format.html { redirect_to heating_systems_url, notice: 'Heating system was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heating_system
      @heating_system = HeatingSystem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heating_system_params
      params[:heating_system]
    end
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doors_helper.rb
module DoorsHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/heating_systems_helper.rb
module HeatingSystemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/insulations_helper.rb
module InsulationsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/roofs_helper.rb
module RoofsHelper
end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/heating_systems/_form.html.erb
<%= form_for @heating_system, :html => { :class => 'form-horizontal form-model' } do |f| %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  heating_systems_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/heating_systems/edit.html.erb
<%- model_class = HeatingSystem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => HeatingSystem %></h1>
</div>
<%= render :partial => 'form' %>

app/views/heating_systems/index.html.erb
<%- model_class = HeatingSystem -%>
<div class="page-header">
  <h1><%=t '.title', :default => HeatingSystem %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @heating_systems.each do |heating_system| %>
      <tr>
        <td><%= heating_system.id %></td>
        <td><%=l heating_system.created_at, format: :long %></td>
        <td>
          <%= link_to heating_system_path(heating_system), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to heating_system_path(heating_system), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_heating_system_path,
            :class => 'btn btn-primary' %>

app/views/heating_systems/new.html.erb
<%- model_class = HeatingSystem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => HeatingSystem %></h1>
</div>
<%= render :partial => 'form' %>

app/views/heating_systems/show.html.erb
<%- model_class = HeatingSystem -%>
<div class="page-header">
  <h1><%=t '.title', :default => HeatingSystem %></h1>
</div>

<div class="fieldset">
  <dl>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              heating_systems_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_heating_system_path(@heating_system), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              heating_system_path(@heating_system),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>